### ISSUE TITLE
It stop working when you extract archive with password without provide password

### ISSUE THREAD

**Issue by a1156883061** [techno-express/node-7z-archive#3]
As title says, when you extract archive with password, but don't provide password, the program won't execute anymore.
I hope the program could stop execute and throw an error
For reason: you need input password when you extract archive with password in shell or command line, this will hung the program, I think there should be some process for this situation

**Comment by a1156883061** [comment]
Test Code
VueTest.zip is a archive with password
```import { listArchive, fullArchive } from 'node-7z-archive';
import { resolve } from 'path';

const filePath = resolve('./static/VueTest.zip');
const destDir = resolve('./out-node');
fullArchive(filePath, destDir)
  .progress(data => {
    console.table(data);
  }).then(result => {
    console.log('finished')
    console.table(result)
  })
  .catch(err => {
    console.error('fullArchive error', err);
  });```

**Comment by techno-express** [comment]
How would you test if archive has a password? 

Not sure if the **7zip** application has/does that, if do, it can be incorporated.

However, if you know archive has password, you will need to supply as parameter with call, otherwise no prompting.
This library is a wrapper for 7zip, not sure if it does prompt on command line if requiring password to be typed in.

You will need to test that out, then that feature can be scripted in, but will require another module for interacting with console.
You can submit PR if you wish.

**Comment by a1156883061** [comment]
![neddPass](https://user-images.githubusercontent.com/36263893/108580939-b8411c80-7368-11eb-9a8b-f014fc7e288c.png)
In command line, if file is encrypted, you will be asked to enter password, and this will pause the program, so the script will stop there if there need password but you don't supply password as a parameter.
And I think we don't need a module to interact with console, we just need throw a error when a file is encrypted.
Or could you provide a function that can tell whether a file is encrypted?
Anyway, I think the script just stop executing is not a good behavior.

**Comment by a1156883061** [comment]
```
import { path7za } from '7zip-bin';
import { spawn } from 'child_process';
import { resolve } from 'path';
console.log('7zPath', path7za);

const filePath = './static/VueTest.zip';
console.log('filePath', resolve(filePath));

let index = 1;
const childProcess = spawn(path7za, [
  'e',
  filePath,
  '-o' + resolve('./output'),
  '-y'
]);
childProcess.stdout.on('data', data => {
  console.log('list', data);
  console.log('index', index);
  index += 1;
  if (/password/.test(data)) {
    childProcess.kill()
    // childProcess.stdin.write('13', err => {
    //   childProcess.stdin.end()
    //   console.error('write error', err);
    // });
    // childProcess.stdin.addListener('finish', () => {
    //   console.log('write finish');
    // });
    // childProcess.stdin.addListener('close', () => {
    //   console.log('write closed')
    // })
  }
  // childProcess.stdin.end('123')
});
```

**Comment by a1156883061** [comment]
Maybe you can find out whether a file is encrypted like this?
Test the stdout is include 'Enter passowrd' ?
```
import { path7za } from '7zip-bin';
import { spawn } from 'child_process';
import { resolve } from 'path';
console.log('7zPath', path7za);

const filePath = './static/VueTest.zip';
console.log('filePath', resolve(filePath));

let index = 1;
const childProcess = spawn(path7za, [
  'e',
  filePath,
  '-o' + resolve('./output'),
  '-y'
]);
childProcess.stdout.on('data', data => {
  console.log('list', data);
  console.log('index', index);
  index += 1;
  if (/password/.test(data)) {
    childProcess.kill()
    // childProcess.stdin.write('13', err => {
    //   childProcess.stdin.end()
    //   console.error('write error', err);
    // });
    // childProcess.stdin.addListener('finish', () => {
    //   console.log('write finish');
    // });
    // childProcess.stdin.addListener('close', () => {
    //   console.log('write closed')
    // })
  }
  // childProcess.stdin.end('123')
});
```

**Comment by techno-express** [comment]
> import { path7za } from '7zip-bin';

What is this `7zip-bin`?
No need for any of that, this whole package is self contained, binaries are pulled at install time. 

>Anyway, I think the script just stop executing is not a good behavior.

What is you trying to do? If you know the archive has a **password** you must supply it by options to the script on execution. 
The whole process supposed to be automated on files you know of. 

Anyway, as i see your example, it's checking `stdout` for "password" if seen, throw error. For that to be useful as you have, that would need to be incorporated throughout all package functions.

**Comment by techno-express** [comment]
You could try at the beginning/after line:
https://github.com/techno-express/node-7z-archive/blob/be9c38b9af21ea48ac6f8f20abda100ec4e25bb5/lib/utility.js#L156

```js
let spawn = object.spawned;
let data = object.output;
if (/password/.test(data)) {
    spawned.kill()
});
```

**Comment by a1156883061** [comment]
https://github.com/techno-express/node-7z-archive/blob/be9c38b9af21ea48ac6f8f20abda100ec4e25bb5/lib/utility.js#L156-L159
```
    let onprogress = (object) => {
      let spawn = object.spawn;
      if (/Enter password \(will not be echoed\):/.test(object.output)) {
          spawn.kill();
          throw new Error('need password');
      }
      progress(object.output);
      return args;
    };
```
Thank you for reply,it can solve this problem
However, I think there is a effect on performance...Or it is acceptable?

**Comment by techno-express** [comment]
> However, I think there is a effect on performance...Or it is acceptable?

Not acceptable, would effect performance, since it would run on all calls. 
This is a special use case, cause user should already know file has a password.

I realize now, that you could run a `try/catch` timer inside the `fullArchive(filePath, destDir).progress({})`.
Just throw if not done within the timer set.

_I could also add another **option** to have the user/developer supply, to force routine to run._

**Comment by a1156883061** [comment]
> I realize now, that you could run a `try/catch` timer inside the `fullArchive(filePath, destDir).progress({})`.
> Just throw if not done within the timer set.

Set timer is not a good solution to solve this problem I think, cause it maybe timeout while the file is large enough.
> 
> _I could also add another **option** to have the user/developer supply, to force routine to run._

And I find another trick to solve this, you can supply `p: ''` parameter as a option, supply password option a empty string, so when a archive is not encrypted, the option will be ignored, it will throw a error while the archive is encrypted. However, the empty file will be extracted while the archive is encrypted and the password is wrong.

**Comment by techno-express** [comment]
> And I find another trick to solve this, you can supply `p: ''` parameter as a option, supply password option a empty string, so when a archive is not encrypted, the option will be ignored, it will throw a error while the archive is encrypted. However, the empty file will be extracted while the archive is encrypted and the password is wrong.

So you have tested that? The option is already present.
